from flask import Flask,jsonify
from services.input_sanitizer import sanitize_input
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
app = Flask(__name__)
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=["30 per minute"]
)
@app.before_request
def check_input():
    result=sanitize_input()
    if result:
        return result

@app.route("/health")
def health():
    return {"status": "AI service running"}

@app.route("/test", methods=["POST"])
@limiter.limit("10 per minute")
def test():
    return {"message": "Request successful"}
@app.route("/describe", methods=["POST"])
def describe():
    return {
        "description": "This is a sample compliance description generated by AI"
    }
@app.route("/recommend", methods=["POST"])
def recommend():
    return {
        "recommendations": [
            "Review compliance policy",
            "Update documentation",
            "Schedule audit check"
        ]
    }
@app.route("/categorise", methods=["POST"])
def categorise():
    return {
        "category": "Finance",
        "confidence": 0.92
    }
@app.route("/generate-report", methods=["POST"])
@limiter.limit("10 per minute")   # special limit
def generate_report():
    return {
        "title": "Compliance Report",
        "summary": "All systems are compliant"
    }
@app.errorhandler(429)
def rate_limit_exceeded(e):
    return jsonify({
        "error": "Too many requests",
        "message": "Rate limit exceeded. Try again later."
    }), 429

if __name__ == "__main__":
    app.run(port=5000)